/*
 * Fufezan Mihai, 2012, lab10, ex 10
 *
 * Write a C/C++ program that implements a function for reading from the
 * keyboard some integer values. The function stores the values in a
 * one-dimensional array named A. Write another function that fills a different
 * one-dimensional array B, each element being obtained by subtracting the mean
 * value of the initial values from the corresponding element located in the
 * one-dimensional array A. Write a function that displays a one-dimensional
 * array and use it for A and B one-dimensional array. (use pointers, don’t use
 * global variables).
 */

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>

void read(int *, int);
int mean(int *, int);
void sub_mean(int *, int *, int);
void print(int *, int);

int main() {
  int n;

  printf("Enter the size of the array: ");
  scanf("%d", &n);

  // read a
  int *a = malloc(sizeof(int) * n);
  read(a, n);

  // generate b
  int *b = malloc(sizeof(int) * n);
  sub_mean(a, b, n);

  // print arrays
  puts("\nThe elements of the array are:");
  print(a, n);
  printf("The mean average of the array is %d", mean(a, n));
  puts("\nThe elements of the array generated by substracting the mean average "
       "of the first array from each element are:");
  print(b, n);

  free(a);
  free(b);
}

void read(int *a, int n) {
  // read an array

  for (int i = 0; i < n; i++) {
    printf("[%d] = ", i);
    scanf("%d", a + i);
  }
}

int mean(int *a, int n) {
  // return the average value of an array

  int sum = 0;
  for (int i = 0; i < n; i++)
    sum += a[i];

  return sum / n;
}

void sub_mean(int *a, int *b, int n) {
  // generates a new array by substracting the mean avg of an array from each
  // element

  int m = mean(a, n);
  for (int i = 0; i < n; i++)
    b[i] = a[i] - m;
}

void print(int *a, int n) {
  // print the elements of an array

  for (int i = 0; i < n; i++)
    printf("%d ", a[i]);
}
